name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

      The error Permission to Kmahamadou/raspberrypi_book_store.git denied to github-actions[bot] indicates that the GitHub Actions bot does not have the necessary permissions to push to your repository. This typically happens when the GITHUB_TOKEN is not being correctly used or does not have sufficient permissions.

To resolve this, make sure that the GITHUB_TOKEN is correctly referenced and used in the deployment step. Here is the corrected workflow file:
Correct Workflow Configuration

Update your .github/workflows/deploy.yml to ensure the GITHUB_TOKEN is used for authentication:

yaml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Change to the version your project requires

    - name: Install dependencies
      run: npm install  # Change to 'yarn install' if you are using Yarn

    - name: Build project
      run: npm run build  # Change to 'yarn build' if you are using Yarn

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"


    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        npm install -g gh-pages
        gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
